[package]
name = "wasmtime-adapter-http"
version = "0.1.0"
edition = "2021"

[build-dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dependencies]
anyhow = "1"
wit-component = "0.14"
